# Generated by Django 3.2.7 on 2022-04-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authentication_label',
            field=models.SmallIntegerField(choices=[(1, 'Manual'), (2, 'Social')], default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='authentication_type',
            field=models.SmallIntegerField(choices=[(1, 'Manual'), (2, 'Social')], default=1),
        ),
    ]
