# Generated by Django 3.2.7 on 2022-07-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
