# Generated by Django 3.2.7 on 2022-02-18 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, max_length=50)),
                ('domain_extension', models.CharField(blank=True, max_length=20)),
                ('business_status', models.CharField(blank=True, max_length=30)),
                ('buyer_price', models.IntegerField(blank=True, default=0)),
                ('seller_price', models.IntegerField(blank=True, default=0)),
                ('min_offer', models.IntegerField(blank=True, default=0)),
                ('visits', models.IntegerField(blank=True, default=0)),
                ('video_pitch_leads', models.IntegerField(blank=True, default=0)),
                ('startup_breeders', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('trade_option', models.CharField(blank=True, max_length=20)),
                ('logs', models.JSONField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domains',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('domain', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='domains.domains')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
