# Generated by Django 3.2.7 on 2022-03-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='logs',
        ),
    ]
