# Generated by Django 3.2.7 on 2022-03-17 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0003_add_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Accepted'), (2, 'Decline'), (3, 'Undecided'), (4, 'Deleted')], default=3),
        ),
        migrations.AddField(
            model_name='videos',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='auth.user'),
            preserve_default=False,
        ),
    ]
