# Generated by Django 3.2.7 on 2022-03-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_auto_20220317_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='startup_breeders_switch',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='domains',
            name='trade_switch',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='domainleads',
            name='business_status',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='domain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_domains', to='domains.domains'),
        ),
    ]
