# Generated by Django 3.2.7 on 2022-03-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_auto_20220323_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
