# Generated by Django 3.2.7 on 2022-03-23 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaiton_category', to='domains.category')),
                ('domain_leads', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_domain_leads', to='domains.domainleads')),
                ('from_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaiton_from_request', to=settings.AUTH_USER_MODEL)),
                ('to_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaiton_to_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
