# Generated by Django 3.2.7 on 2022-03-28 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_notification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='trade_option',
        ),
    ]
