# Generated by Django 3.2.7 on 2022-03-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0010_remove_domains_trade_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='trade_option',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
