# Generated by Django 3.2.7 on 2022-04-02 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0011_domains_trade_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='advertisement_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='SponsoredHeadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_price', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_category', to='domains.category')),
                ('domain', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_domain', to='domains.domains')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startupheadlines',
            },
        ),
    ]
