# Generated by Django 3.2.7 on 2022-04-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0012_auto_20220402_1115'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sponsoredheadlines',
            table='sponsoredheadlines',
        ),
    ]
