# Generated by Django 3.2.7 on 2022-04-11 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0014_order_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_ids', models.JSONField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('unit_price', models.IntegerField(blank=True, default=0)),
                ('sub_total', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartdetails_cart', to='domains.cart')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartdetails_category', to='domains.category')),
            ],
            options={
                'db_table': 'cartdetails',
            },
        ),
    ]
