# Generated by Django 3.2.7 on 2022-04-13 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0015_auto_20220411_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Open For Sale'), (2, 'Negotiation'), (3, 'Broker'), (4, 'Sold')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.SmallIntegerField(choices=[(1, 'Online'), (2, 'Cash On Delivery')], default=2),
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('status', models.SmallIntegerField(choices=[(1, 'Initial Offer'), (2, 'Counter Offer'), (3, 'Buyer Offer'), (4, 'Approved'), (5, 'Assigned To Broker'), (6, 'Bidding War'), (7, 'Startup Breeder Budget')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('domain_leads', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_domain_leads', to='domains.domainleads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'negotiation',
            },
        ),
    ]
