# Generated by Django 3.2.7 on 2022-07-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0017_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='is_approved',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Denied')], default=1),
        ),
    ]
